import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css';
import Movie from './components/Movie';

const Home: NextPage = () => {
  const [popular, setPopular] = useState([]);
  const [filtered, setFiltered] = useState([]);
  const [activeGenera, setActiveGenera] = useState(0);

  useEffect(() => {
    fetchPopular();
    history.scrollRestoration = 'auto';
  }, []);

  const fetchPopular = async () => {
    //! 기본 fetch로 데이터 가져올 경우 되돌아 왔을 때는 무조건 스크롤이 최상단으로 고정됨
    const data = await fetch(
      'https://api.themoviedb.org/3/movie/popular?api_key=d1eb186c558e65b045af69086018917f&language=en-US&page=1'
    );
    const movies = await data.json();

    setPopular(movies.results);
    setFiltered(movies.results);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next Scroll 뒤로가기 유지를 위한 학습중</h1>

        {filtered.map((movie: any) => {
          return <Movie key={movie.id} movie={movie} />;
        })}

        <Link href="/detail">
          <a>go Detail</a>
        </Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
